alter table SPMK_CT_PHIEU_XUAT add constraint FK_SPMK_CT_PHIEU_XUAT_ON_PHIEU_XUAT foreign key (PHIEU_XUAT_ID) references SPMK_PHIEU_XUAT_KHO(ID);
alter table SPMK_CT_PHIEU_XUAT add constraint FK_SPMK_CT_PHIEU_XUAT_ON_HANG_HOA foreign key (HANG_HOA_ID) references SPMK_HANG_HOA(ID);
create index IDX_SPMK_CT_PHIEU_XUAT_ON_PHIEU_XUAT on SPMK_CT_PHIEU_XUAT (PHIEU_XUAT_ID);
create index IDX_SPMK_CT_PHIEU_XUAT_ON_HANG_HOA on SPMK_CT_PHIEU_XUAT (HANG_HOA_ID);
