alter table SPMK_CT_PHIEU_MUA add constraint FK_SPMK_CT_PHIEU_MUA_ON_PHIEU_MUA foreign key (PHIEU_MUA_ID) references SPMK_PHIEU_MUA_HANG(ID);
alter table SPMK_CT_PHIEU_MUA add constraint FK_SPMK_CT_PHIEU_MUA_ON_HANG_HOA foreign key (HANG_HOA_ID) references SPMK_HANG_HOA(ID);
create index IDX_SPMK_CT_PHIEU_MUA_ON_PHIEU_MUA on SPMK_CT_PHIEU_MUA (PHIEU_MUA_ID);
create index IDX_SPMK_CT_PHIEU_MUA_ON_HANG_HOA on SPMK_CT_PHIEU_MUA (HANG_HOA_ID);
